### ISSUE TITLE
jmv-desc attribute

### ISSUE THREAD

**Issue by wdkeyzer** [sjentsch/jmvReadWrite#11]
Hi and congrats with your new package! I've been looking into some use of the labels_vars_omv() function and how you can add a custom variable label as an attribute to your variables using 'jmv-desc' as a name for this attribute. To my surprise, when the {jmv} package is then used to perform some analysis in R, the resulting output does not present  this variable label but the original variable name. Is there a way to let the custom labels show up in the output from {imv} commands just like it is the case in the GUI when a variable description is entered?

**Comment by sjentsch** [comment]
Hi, I am afraid, I am not the right address to ask for this. Calculations and output within `jmv` are part of the jamovi project, so this issue should rather be submitted to https://github.com/jamovi/jmv/issues
However, I am afraid, it won't end up very high on the priority list as it is rather cosmetic. Generally, the problem with labels is that they tend to be (much) longer than variable names, messing up the formatting of the output (tables and figures).
One thing you may try is to just assign what you want as output to the variable names.
```
data <- ToothGrowth
names(data) <- c("Length of the odontoblasts", "Supplement type (vitamin C or orange juice)", "Dose in milligrams/day")
jmv::ANOVA(dep = "Length of the odontoblasts", factors = c("Supplement type (vitamin C or orange juice)", "Dose in milligrams/day"), data = data)

```
Hope this helps!
Cheers, Sebastian

**Comment by sjentsch** [comment]
Not really an issue (i.e., nothing is wrong with the code base).
